export enum GeneralAtlasKey {
  TreePineSmall = 1,
  DoorClosedHorizontal,
  DoorOpen,
  FlowerRed,
  FlowerPurple,
  FlowerWhite,
  BoulderSmall,
  TerrainGeneric,
  TreeOakLarge1,
  Shrubbery1,
  Shrubbery2,
  Shrubbery3,
  Leaves1,
  Leaves2,
  Leaves3,
  Leaves4,
  Leaves5,
  TreeOakLarge2,
  TreeOakLarge3,
  TreeOakLarge4,
  BerryBushPlain,
  BerryBushRipe,
  BoulderLarge,
  DoorClosedVertical,
}
